#pragma once

enum class EKeyState
{
    PRESSED,
    RELEASED,
    HELD,
    NONE
};

#define GNOTE_KEY_SPACE 32
#define GNOTE_KEY_APOSTROPHE 39 /* ' */
#define GNOTE_KEY_COMMA 44      /* , */
#define GNOTE_KEY_MINUS 45      /* - */
#define GNOTE_KEY_PERIOD 46     /* . */
#define GNOTE_KEY_SLASH 47      /* / */
#define GNOTE_KEY_0 48
#define GNOTE_KEY_1 49
#define GNOTE_KEY_2 50
#define GNOTE_KEY_3 51
#define GNOTE_KEY_4 52
#define GNOTE_KEY_5 53
#define GNOTE_KEY_6 54
#define GNOTE_KEY_7 55
#define GNOTE_KEY_8 56
#define GNOTE_KEY_9 57
#define GNOTE_KEY_SEMICOLON 59 /* ; */
#define GNOTE_KEY_EQUAL 61     /* = */
#define GNOTE_KEY_A 65
#define GNOTE_KEY_B 66
#define GNOTE_KEY_C 67
#define GNOTE_KEY_D 68
#define GNOTE_KEY_E 69
#define GNOTE_KEY_F 70
#define GNOTE_KEY_G 71
#define GNOTE_KEY_H 72
#define GNOTE_KEY_I 73
#define GNOTE_KEY_J 74
#define GNOTE_KEY_K 75
#define GNOTE_KEY_L 76
#define GNOTE_KEY_M 77
#define GNOTE_KEY_N 78
#define GNOTE_KEY_O 79
#define GNOTE_KEY_P 80
#define GNOTE_KEY_Q 81
#define GNOTE_KEY_R 82
#define GNOTE_KEY_S 83
#define GNOTE_KEY_T 84
#define GNOTE_KEY_U 85
#define GNOTE_KEY_V 86
#define GNOTE_KEY_W 87
#define GNOTE_KEY_X 88
#define GNOTE_KEY_Y 89
#define GNOTE_KEY_Z 90
#define GNOTE_KEY_LEFT_BRACKET 91  /* [ */
#define GNOTE_KEY_BACKSLASH 92     /* \ */
#define GNOTE_KEY_RIGHT_BRACKET 93 /* ] */
#define GNOTE_KEY_GRAVE_ACCENT 96  /* ` */
#define GNOTE_KEY_WORLD_1 161      /* non-US #1 */
#define GNOTE_KEY_WORLD_2 162      /* non-US #2 */

/* Function keys */
#define GNOTE_KEY_ESCAPE 256
#define GNOTE_KEY_ENTER 257
#define GNOTE_KEY_TAB 258
#define GNOTE_KEY_BACKSPACE 259
#define GNOTE_KEY_INSERT 260
#define GNOTE_KEY_DELETE 261
#define GNOTE_KEY_RIGHT 262
#define GNOTE_KEY_LEFT 263
#define GNOTE_KEY_DOWN 264
#define GNOTE_KEY_UP 265
#define GNOTE_KEY_PAGE_UP 266
#define GNOTE_KEY_PAGE_DOWN 267
#define GNOTE_KEY_HOME 268
#define GNOTE_KEY_END 269
#define GNOTE_KEY_CAPS_LOCK 280
#define GNOTE_KEY_SCROLL_LOCK 281
#define GNOTE_KEY_NUM_LOCK 282
#define GNOTE_KEY_PRINT_SCREEN 283
#define GNOTE_KEY_PAUSE 284
#define GNOTE_KEY_F1 290
#define GNOTE_KEY_F2 291
#define GNOTE_KEY_F3 292
#define GNOTE_KEY_F4 293
#define GNOTE_KEY_F5 294
#define GNOTE_KEY_F6 295
#define GNOTE_KEY_F7 296
#define GNOTE_KEY_F8 297
#define GNOTE_KEY_F9 298
#define GNOTE_KEY_F10 299
#define GNOTE_KEY_F11 300
#define GNOTE_KEY_F12 301
#define GNOTE_KEY_F13 302
#define GNOTE_KEY_F14 303
#define GNOTE_KEY_F15 304
#define GNOTE_KEY_F16 305
#define GNOTE_KEY_F17 306
#define GNOTE_KEY_F18 307
#define GNOTE_KEY_F19 308
#define GNOTE_KEY_F20 309
#define GNOTE_KEY_F21 310
#define GNOTE_KEY_F22 311
#define GNOTE_KEY_F23 312
#define GNOTE_KEY_F24 313
#define GNOTE_KEY_F25 314
#define GNOTE_KEY_KP_0 320
#define GNOTE_KEY_KP_1 321
#define GNOTE_KEY_KP_2 322
#define GNOTE_KEY_KP_3 323
#define GNOTE_KEY_KP_4 324
#define GNOTE_KEY_KP_5 325
#define GNOTE_KEY_KP_6 326
#define GNOTE_KEY_KP_7 327
#define GNOTE_KEY_KP_8 328
#define GNOTE_KEY_KP_9 329
#define GNOTE_KEY_KP_DECIMAL 330
#define GNOTE_KEY_KP_DIVIDE 331
#define GNOTE_KEY_KP_MULTIPLY 332
#define GNOTE_KEY_KP_SUBTRACT 333
#define GNOTE_KEY_KP_ADD 334
#define GNOTE_KEY_KP_ENTER 335
#define GNOTE_KEY_KP_EQUAL 336
#define GNOTE_KEY_LEFT_SHIFT 340
#define GNOTE_KEY_LEFT_CONTROL 341
#define GNOTE_KEY_LEFT_ALT 342
#define GNOTE_KEY_LEFT_SUPER 343
#define GNOTE_KEY_RIGHT_SHIFT 344
#define GNOTE_KEY_RIGHT_CONTROL 345
#define GNOTE_KEY_RIGHT_ALT 346
#define GNOTE_KEY_RIGHT_SUPER 347
#define GNOTE_KEY_MENU 348

#define GNOTE_MOUSE_BUTTON_1 0
#define GNOTE_MOUSE_BUTTON_2 1
#define GNOTE_MOUSE_BUTTON_3 2
#define GNOTE_MOUSE_BUTTON_4 3
#define GNOTE_MOUSE_BUTTON_5 4
#define GNOTE_MOUSE_BUTTON_6 5
#define GNOTE_MOUSE_BUTTON_7 6
#define GNOTE_MOUSE_BUTTON_8 7
#define GNOTE_MOUSE_BUTTON_LAST GNOTE_MOUSE_BUTTON_8
#define GNOTE_MOUSE_BUTTON_LEFT GNOTE_MOUSE_BUTTON_1
#define GNOTE_MOUSE_BUTTON_RIGHT GNOTE_MOUSE_BUTTON_2
#define GNOTE_MOUSE_BUTTON_MIDDLE GNOTE_MOUSE_BUTTON_3
